# Generated by Django 2.0.5 on 2020-01-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiph', '0002_auto_20200111_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
