# Generated by Django 2.0.5 on 2020-07-11 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swiph', '0006_auto_20200116_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicMachineLearnigDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('asm', models.FloatField()),
                ('P_turb_des', models.FloatField()),
                ('T_cold_ref', models.FloatField()),
                ('nModBoil', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineLearnigDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('I_bn_des', models.FloatField()),
                ('T_cold_ref', models.FloatField()),
                ('x_b_des', models.FloatField()),
                ('nLoops', models.IntegerField()),
                ('P_turb_des', models.FloatField()),
                ('heat_sink_dP_frac', models.FloatField()),
                ('nModBoil', models.IntegerField()),
                ('theta_dep', models.FloatField()),
                ('theta_stow', models.FloatField()),
                ('V_wind_max', models.FloatField()),
                ('ColAz', models.FloatField()),
                ('T_amb_des_sf', models.FloatField()),
                ('SCA_drives_elec', models.FloatField()),
                ('Pipe_hl_coef', models.FloatField()),
                ('csp_lf_sf_water_per_wash', models.FloatField()),
                ('csp_lf_sf_washes_per_year', models.FloatField()),
                ('fP_hdr_c', models.FloatField()),
                ('fP_sf_boil', models.FloatField()),
                ('fP_hdr_h', models.FloatField()),
                ('T_fp', models.FloatField()),
                ('eta_pump', models.FloatField()),
                ('e_startup', models.FloatField()),
                ('A_aperture', models.FloatField()),
                ('L_col', models.FloatField()),
                ('TrackingError', models.FloatField()),
                ('GeomEffects', models.FloatField()),
                ('rho_mirror_clean', models.FloatField()),
                ('dirt_mirror', models.FloatField()),
                ('error', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ScriptTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='create_mldb', max_length=60)),
                ('starting_date', models.DateTimeField(auto_now_add=True)),
                ('ending_date', models.DateTimeField(auto_now=True, null=True)),
                ('keep_running', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='basicmachinelearnigdb',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swiph.ErrorCode'),
        ),
    ]
