# Generated by Django 2.0.5 on 2020-08-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiph', '0007_auto_20200711_0222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicMachineLearnigDB',
            new_name='BasicMachineLearningDB',
        ),
        migrations.RenameModel(
            old_name='MachineLearnigDB',
            new_name='MachineLearningDB',
        ),
    ]
